### ISSUE TITLE
Connect the Django with PostgreSQL DB

### ISSUE THREAD

**Issue by dor4231** [PositiveYou/NetHood#18]
In order to make this application as robust and scalable as possible, we have to start with a solid and strong DB.

PostgreSQL is my choice of that because of its flexibility with JSON fields.

The Goal here is to create a server that will be available for all of us online. We will create a secret key to get into this server with our local Django servers.

**Comment by YoadElkayam** [comment]
[NetHoodDB.pdf](https://github.com/PositiveYou/NetHood/files/2398733/NetHoodDB.pdf)
A sketch of our database.
to understand the relations more go to this link > https://dbdiagram.io/d/5ba2a7f66f404a00142e15b4
if you need username and password ask me in Slack.

**Comment by dor4231** [comment]
I have created a user in [elephantsql.com](elephantsql.com) with one instance of postgreSQL
