### ISSUE TITLE
myHood - Notification center

### ISSUE THREAD

**Issue by dor4231** [PositiveYou/NetHood#28]
What exactly the user see in this section?
How does the user get into this section?
How frequently the information updates?
Should we push notification to the user's device?
What will be the order of appearance for each pace of information?

Should be defined in detail.

**Comment by YoadElkayam** [comment]
https://docs.google.com/document/d/18O4T8dgfRcttktphbZVMgqttGhFWtZMkoq-u5zmtbKY/edit

Please, do not change the doc. if you have any ideas or notes use the suggesting tab.

**Comment by YoadElkayam** [comment]
[Notification center.docx](https://github.com/PositiveYou/NetHood/files/2430840/Notification.center.docx)
