### ISSUE TITLE
myGroups - Group news

### ISSUE THREAD

**Issue by dor4231** [PositiveYou/NetHood#29]
What is exactly the information this section displays?
How is it different from the myHood section?
Where should the user find this information in the app?
What is the priority and order of the information paces appearance?

Please define in detail.

**Comment by YoadElkayam** [comment]
https://docs.google.com/document/d/12PrprUJ3hAUSYGdJ0mIzVPl4aWk0IgY9UUcbEs2pyCM/edit#
