### ISSUE TITLE
Display of Events - The main feature of this app

### ISSUE THREAD

**Issue by dor4231** [PositiveYou/NetHood#30]
Where the user can find this section?
Which type of events does the user see?
What exactly happens when a user interacts with an event?
In which way we will display the events? (Map? List? Cards? All of them?) - _This is a big one, can be split into four different issues (definitions)._
There is a way to create events?
Which features this section have?
What exactly the user do in this section? What is the main goal?

**Comment by YoadElkayam** [comment]
https://docs.google.com/document/d/1tTJuIwkFzbrD3lJwJ3H0Oov5NkTcbZ___qIHhxUYG1Q/edit#
