### ISSUE TITLE
Events - as an object in the system

### ISSUE THREAD

**Issue by dor4231** [PositiveYou/NetHood#31]
What are the properties of each event? (Which information does it hold?)
How to create an event?
How to delete an event?
Who can create the event?
Who can get the event?
Do we have a level of permissions for each event?

**Comment by YoadElkayam** [comment]
https://docs.google.com/document/d/1tTJuIwkFzbrD3lJwJ3H0Oov5NkTcbZ___qIHhxUYG1Q/edit#heading=h.qpq18ztuy7w9
