### ISSUE TITLE
Make at least 500 Form fillers

### ISSUE THREAD

**Issue by dor4231** [PositiveYou/NetHood#52]
Each one of the team members will have to send the form to anyone he knows that fit our profile and targeted clients.

People that have more connection with others are **highly recommended**.

**Comment by dor4231** [comment]
We have now 231 people who responded to this form! 
Keep up the good work! We are almost there!

**Comment by YoadElkayam** [comment]
assigning to shmuliq

**Comment by MarinaRappoport** [comment]
sent another 30 links

**Comment by dor4231** [comment]
312 is quite a lot... But still not enough. I mean, the results for the last 50 responses are keeping the statistics as before. We will have to get at least 100 more and see that the statistics still not changing to be more confident about the real world picture of NetHood and the chance it will be something great

What do you think?

**Comment by dor4231** [comment]
What do you say about translating this into other two languages (Russian and English)?

**Comment by YoadElkayam** [comment]
let's do it today

**Comment by dor4231** [comment]
We have decided not to wait until all 500 will respond to the survey.

I am closing this issue for that reason.
